version: '3'

services:
    web:
        build: .
        image: takacsmark/swarm-example:1.0
    nginx:
        build: ./nginx 
        restart: always
        volumes:
            - static_volume:/code/static/ 
        ports:
            - "80:80" 
