version: '3'

services:
    web:
        image: debian:latest
    tomcat:
        image: tomcat:latest
        ports:
            - "8080:8080" 
    nginx:
        image: nortonts/nginx_conf:latest
        restart: always
        ports:
            - "80:80" 
