version: '3'
volumes: 
  postgres_data:
services:
    web:
        image: nortonts/nginx_conf:latest
        restart: always
        ports:
            - "80:80" 
    tomcat:
        image: tomcat:latest
        ports:
            - "8080:8080" 
    postgres:
        image: postgres
        hostname: postgres
        ports:
        - "6543:6543"
        environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: TEST_SM
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "5432:5432"
        environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped    

