version: '3'
volumes: 
  postgres_data:
services:
    web:
        image: nortonts/nginx_conf:latest
        restart: always
        ports:
            - "80:80" 
    tomcat:
        image: tomcat:latest
        ports:
            - "8080:8080" 
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "6543:6543"
    
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 5432
        ports:
            - "5432:5432"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
        volumes:
        db-data:
        

