version: '3'

services:
    web:
        build: .
        image: takacsmark/swarm-example:1.0
    nginx:
        image: nortonts/nginx_conf:latest
        restart: always
        ports:
            - "80:80" 
