version: '3'
volumes: 
  postgres_data:
services:
    web:
        image: nortonts/nginx_conf:latest
        restart: always
        ports:
            - "80:80" 
    tomcat:
        image: tomcat:latest
        expose:
            - "8080:8080" 
    db:
        image: postgres:12.4
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            POSTGRES_HOST_AUTH_METHOD: "trust"
    pg-admin:
        image: dpage/pgadmin4
        restart: always
        environment: 
            PGADMIN_DEFAULT_EMAIL: "test@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "pgpass" 
        depends_on: 
            - db  
        ports:
            - "5432:5432"     

