version: '3'

services:
    web:
        build: .
        image: takacsmark/swarm-example:1.0
        networks:
            - mynet
    nginx:
        image: nginx:1.19.5
        restart: always
        volumes:
        - ./nginx/:/etc/nginx/conf.d/
        ports:
        - "80:80" 
        networks:
            - mynet     
networks:
    mynet: