#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker push") {
            steps {
                echo " ============== building ubuntu =================="
                dir ('Docker')
                sh 'docker compose up .'
            }
        }
    }
}